# Generated by Django 4.0 on 2021-12-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=30000)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('articles', models.ManyToManyField(to='api.Article')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('corrent_answer_no', models.IntegerField()),
                ('answer1', models.CharField(max_length=256)),
                ('explanation1', models.CharField(max_length=256)),
                ('answer2', models.CharField(max_length=256)),
                ('explanation2', models.CharField(max_length=256)),
                ('answer3', models.CharField(max_length=256)),
                ('explanation3', models.CharField(max_length=256)),
                ('answer4', models.CharField(max_length=256)),
                ('explanation4', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TinderSwipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.BooleanField()),
                ('explanation', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='challenge',
            name='questions',
            field=models.ManyToManyField(to='api.MultipleChoiceQuestion'),
        ),
    ]
