# Generated by Django 4.0 on 2022-01-17 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_article_challenge_module_multiplechoicequestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxScore', models.IntegerField()),
                ('question', models.CharField(max_length=256)),
                ('corrent_answer_no', models.IntegerField()),
                ('answer1', models.CharField(max_length=256)),
                ('explanation1', models.CharField(max_length=256)),
                ('answer2', models.CharField(max_length=256)),
                ('explanation2', models.CharField(max_length=256)),
                ('answer3', models.CharField(max_length=256)),
                ('explanation3', models.CharField(max_length=256)),
                ('answer4', models.CharField(max_length=256)),
                ('explanation4', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='TinderSwipe',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='questions',
        ),
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 36, 55, 686009)),
        ),
        migrations.AddField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 36, 55, 686009)),
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.AddField(
            model_name='challenge',
            name='activities',
            field=models.ManyToManyField(to='api.Activity'),
        ),
        migrations.AddField(
            model_name='module',
            name='activities',
            field=models.ManyToManyField(to='api.Activity'),
        ),
    ]
