# Generated by Django 4.0 on 2022-01-17 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_activity_delete_tinderswipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 38, 34, 840296)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 38, 34, 840296)),
        ),
    ]
