# Generated by Django 4.0 on 2022-01-17 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_challenge_valid_from_alter_challenge_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 38, 40, 795182)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 21, 38, 40, 796183)),
        ),
    ]
