# Generated by Django 4.0 on 2022-01-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_answer_question_alter_challenge_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 20, 24, 38, 470718)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 20, 24, 38, 470718)),
        ),
    ]
