# Generated by Django 4.0 on 2022-01-23 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_readinganswer_readingquestion_testanswer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingpart',
            old_name='reading',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='readingquestion',
            old_name='activity',
            new_name='part',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 0, 53, 3, 267805)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 0, 53, 3, 267805)),
        ),
    ]
