# Generated by Django 4.0 on 2022-01-24 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_challenge_valid_from_alter_challenge_valid_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modules_progress',
            new_name='current_progress',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 18, 42, 45, 977942)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 18, 42, 45, 977942)),
        ),
    ]
